module.exports = {
  apps: [
    {
      name: "sijagaair-api",
      cwd: __dirname,
      script: "npm",
      args: "run start:api",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
    },
    {
      name: "sijagaair-mqtt-collector",
      cwd: __dirname,
      script: "npm",
      args: "run start:collector",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
    },
    {
      name: "sijagaair-data-processing",
      cwd: __dirname,
      script: "npm",
      args: "run start:processing",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
    },
    {
      name: "sijagaair-notification-gateway",
      cwd: __dirname,
      script: "npm",
      args: "run start:notification",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
    },
    {
      name: "sijagaair-tunnel",
      cwd: __dirname,
      script: "cloudflared",
      args: ["tunnel", "--url", "http://localhost:3001"],
      interpreter: "none",
      exec_mode: "fork",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
    },
  ],
};
